site_name: Nav Numbering Showcase
site_url: https://example.com/
repo_url: https://github.com/matusdrobuliak66/mkdocs-nav-numbering-plugin

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search
  - nav-numbering:
      preserve_anchor_ids: true

nav:
  - Home: index.md
  - Getting Started:
      - Install: guide/install.md
      - Quick Start: guide/quick-start.md
  - User Guide:
      - Configuration: guide/configuration.md
      - Tips & Tricks: guide/tips.md
  - Reference:
      - MkDocs Commands: reference/cli.md
      - API: reference/api.md
  - FAQ: faq.md


markdown_extensions:
  - attr_list  # Required!